# Generated by Django 3.0.4 on 2020-05-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200525_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='hot',
        ),
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
