# Generated by Django 3.0.4 on 2020-05-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200526_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
