# Generated by Django 3.0.4 on 2020-06-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20200526_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='detail',
            new_name='content',
        ),
    ]
