# Generated by Django 3.0.4 on 2020-06-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20200604_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
