# Generated by Django 3.0.4 on 2020-06-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_news_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='testfield',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
