# Generated by Django 3.0.4 on 2020-05-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200511_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmessage',
            name='subject',
        ),
    ]
